# Generated by Django 5.1.4 on 2025-01-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
