# Generated by Django 5.1.4 on 2025-01-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
